name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          # config_display: columns
          config_display: large
          # config_octicon: yes
          config_output: svg
          config_timezone: Asia/Jakarta
          # config_twemoji: yes

          # Base Repositories
          repositories_affiliations: owner, collaborator, organization_member

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Activity
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_activity_timestamps: yes

          # Plugin Code Snippet of the day
          # plugin_code: yes
          # plugin_code_lines: 12
          # plugin_code_load: 100
          # plugin_code_days: 3
          # plugin_code_languages: javascript, typescript, python, rust, java

          # Followup
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

          # Gists
          # plugin_gists: yes
          
          # Habits
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          # Isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Leetcode
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skiils
          plugin_leetcode_user: Dimas Tri Mustakim

          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: HTML
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          # Notable
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit

          # People
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          # Reactions
          # plugin_reactions: yes
          # plugin_reactions_display: absolute
          # plugin_reactions_limit: 200
          # plugin_reactions_limit_discussions: 100
          # plugin_reactions_limit_discussions_comments: 100
          # plugin_reactions_limit_issues: 100

          # Repositories
          # plugin_repositories: yes
          # plugin_repositories_featured: all
          # plugin_repositories_pinned: 2
          # plugin_repositories_starred: 2
          # plugin_repositories_random: 2
          # plugin_repositories_forks: no
          # plugin_repositories_affiliations: owner, collaborator, organization_member

          # Stargazers
          # plugin_stargazers: yes
          # plugin_stargazers_charts: yes
          # plugin_stargazers_charts_type: chartist
          # plugin_starlists: yes
          # plugin_starlists_limit: 2
          # plugin_starlists_limit_languages: 8
          # plugin_starlists_limit_repositories: 2
          # plugin_starlists_shuffle_repositories: yes

          # RSS
          plugin_rss: yes
          plugin_rss_source: https://medium.com/feed/@tridim
          plugin_rss_limit: 4

          # Stars
          # plugin_stars: yes
          # plugin_stars_limit: 4

          # Topics
          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_topics_limit: 15

          # Traffic
          plugin_traffic: yes
          # plugin_traffic_skipped: 